### ISSUE TITLE
ベースリンク目標位置

### ISSUE THREAD

**Issue by atom-2003** [atom-2003/vnoid#2]
# 課題
ベースリンク目標位置が重心の目標位置と等しいことになっているが，もう少し精度を上げたい

# 解決策（一例）
三質点モデルとか，もしかしたらchoreonoid標準のCalcCenterOfMass()が有効化もしれない（シミュレータから直接取得してる関数なら使ってはならないが）．

# 難易度
普通

**Comment by atom-2003** [comment]
課題として書いたことは嘘でした．どちらにせよ改善の余地はまだ残っています

**Comment by MIYATANIKoki** [comment]
宮谷やります(MIYATANIKoki)

**Comment by atom-2003** [comment]
逆運動学については重心位置の計算をこちらで改善することにしました @MIYATANIKoki 
色々と検討ありがとうございます．
